### PR TITLE
Add dubbo3 support

### PR DESCRIPTION
**Pull request by ShenFeng312**

### CODE REVIEW

**Comment by ShenFeng312** [comment]
@jcchavezs

**Comment by jcchavezs** [comment]
Thanks for this. Let @shakuzen and me review the code and get back to you.

**Comment by jcchavezs** [comment]
Overall looks good. Let's also ping @jeqo

**Comment by ShenFeng312** [comment]
@shakuzen @jeqo

**Comment by ShenFeng312** [comment]
Hi :) Any ideas when this will be merged?
@jcchavezs @shakuzen @jeqo

**Comment by jcchavezs** [comment]
Let me get some other reviewers

**Comment by ShenFeng312** [comment]
I will open a new PR to support this

**Pull request closed without merging**
