### PR TITLE
Support for Jakarta JMS specification

### PR DESCRIPTION
**Pull request by reta**
Support for Jakarta JMS specification 3.0+. Largely adapted from the existing JMS support. 
Closes https://github.com/openzipkin/brave/issues/1352.

### CODE REVIEW

**Review by jcchavezs — APPROVED** [review]

**Comment by raverone** [comment]
Hi :) Any ideas when this will be merged?

**Comment by reta** [comment]
@shakuzen could you please take a look? thank you

**Comment by jcchavezs** [comment]
Ping @jeqo

**Comment by raverone** [comment]
Is it okay now to exclude jeqo from the reviewers and merge the PR? :sweat_smile:

**Comment by reta** [comment]
> LGTM. Thanks @reta for taking on this work. Maybe we need to update the copyright year now that it is 2023? Sorry for the late review.

Thanks a lot for review, @shakuzen, technically the copyright year is correct - the change was done in 2022 :)

**Comment by jcchavezs** [comment]
I will merge it.

**Comment by raverone** [comment]
Hi, exuse me, but when this PR could be merged? And when new Brave version with this changes will be released?

**Comment by jcchavezs** [comment]
Sure.

**Comment by jcchavezs** [comment]
5.15.0 is out now https://github.com/openzipkin/brave/releases/tag/5.15.0

**Comment by reta** [comment]
Thanks a lot @jcchavezs !

**Comment by raverone** [comment]
Hi, thanks for merging this PR.
But the release 5.15.0 is not available in mvnrepository.com.
Is it intentional?
If yes, then could you please tell when it will be available?

**Comment by reta** [comment]
> If yes, then could you please tell when it will be available?

@raverone the deploy action failed [1] and you are right, artifacts are not published, @jeqo @jcchavezs could you folks please help?

[1] https://github.com/openzipkin/brave/actions/runs/4014424826/jobs/6995827578

**Comment by jcchavezs** [comment]
I was looking into this with no success. I pinged @llinder but maybe
@shakuzen can also help.

**Comment by shakuzen** [comment]
Indeed the release job failed, but it looks like artifacts were published to central a few hours ago. mvnrepository.com is not the canonical source of what is in maven central, and it tends to take some time for it to sync changes from maven central. You can search maven central directly and see the artifacts there for 5.15.0: https://central.sonatype.com/search?q=io.zipkin.brave

**Comment by reta** [comment]
> Indeed the release job failed, but it looks like artifacts were published to central a few hours ago. mvnrepository.com is not the canonical source of what is in maven central, and it tends to take some time for it to sync changes from maven central. You can search maven central directly and see the artifacts there for 5.15.0: https://central.sonatype.com/search?q=io.zipkin.brave

Thanks @shakuzen , I confirm that now artifacts are available.

**Comment by raverone** [comment]
Yes, thanks guys, the new brave-instrumentation-jakarta-jms is now available, I just included it in my project! :partying_face:  :raised_hands:
Although there still might be one tiny issue: looks like this new artifact is not included in the brave-bom. I was not able to use it without specifying a version. Could you please check this?

**Comment by reta** [comment]
> Yes, thanks guys, the new brave-instrumentation-jakarta-jms is now available, I just included it in my project! 🥳 🙌 Although there still might be one tiny issue: looks like this new artifact is not included in the brave-bom. I was not able to use it without specifying a version. Could you please check this?

@raverone here we are https://github.com/openzipkin/brave/pull/1361

**Comment by raverone** [comment]
Thanks you all guys, you are the best! 🙂

**Pull request merged**
