### PR TITLE
Convenience constructor to BraveServletFilter/JerseyClientTraceFilter

### PR DESCRIPTION
**Pull request by epabst**
This reduces the learning curve for using Brave
and makes it easier to wire these into an application.

### CODE REVIEW

**Comment by epabst** [comment]
FWIW, this build failure looks like an intermittent failure, possibly due to a concurrent test.  
"mvn clean install" passed for me.

**Comment by adriancole** [comment]
public constructors are usually a little evil vs factor or builders wrt maintenance. Particularly as there are other various customization requests in-flight (like #265) I'm apprehensive about merging this right now.

**Comment by adriancole** [comment]
ps fwiw I also think that it would be useful to use Brave as a starting point as opposed to elements provided by Brave. My guess is that the reason this wasn't done initially was in support of mocking (ex mocking is easier when you don't have to navigate an object graph like Brave)

**Comment by epabst** [comment]
I really like the idea of making it easy to mock, and yes providing simply a Brave is much simpler for normal usage.  Providing two constructors, one with a Brave, and one with the mockable types may be the sweet spot.

**Comment by epabst** [comment]
@adriancole Updated to only add a single constructor each, that just takes a Brave.

**Comment by adriancole** [comment]
I don't think there's any design we'll end up with where public constructors become more used. How about revising to builder pattern instead (and deprecate the old constructor)?

```java
  public static Builder builder() {
    return new Builder();
  }

  public final static class Builder {
    private ServerRequestInterceptor requestInterceptor;
--snip--

    public Builder requestInterceptor(ServerRequestInterceptor requestInterceptor) {
      this.requestInterceptor = requestInterceptor;
      return this;
    }
--snip--

    public BraveServletFilter build() {
      // conditionally set anything..
      return new BraveServletFilter(this);
    }

    Builder() { // intentionally hidden
    }
  }

  BraveServletFilter(Builder builder) { // intentionally hidden
    this.requestInterceptor = builder.requestInterceptor;
--snip--
```

**Pull request closed without merging**
