### PR TITLE
Can be customized Clock.

### PR DESCRIPTION
**Pull request by wangliang1986**
Can be customized Clock.
For example: using database TickClock.

### CODE REVIEW

**Comment by adriancole** [comment]
how is this different than Tracing.Builder.clock() for you?

ex this exists:
```java
    /**
     * Assigns microsecond-resolution timestamp source for operations like {@link Span#start()}.
     * Defaults to JRE-specific platform time.
     *
     * <p>Note: timestamps are read once per trace, then {@link System#nanoTime() ticks}
     * thereafter. This ensures there's no clock skew problems inside a single trace.
     *
     * See {@link Tracing#clock(TraceContext)}
     */
    public Builder clock(Clock clock) {
      if (clock == null) throw new NullPointerException("clock == null");
      this.clock = clock;
      return this;
    }
```

**Comment by wangliang1986** [comment]
> 
> 
> how is this different than Tracing.Builder.clock() for you?
> 
> ex this exists:
> 
> ```java
>     /**
>      * Assigns microsecond-resolution timestamp source for operations like {@link Span#start()}.
>      * Defaults to JRE-specific platform time.
>      *
>      * <p>Note: timestamps are read once per trace, then {@link System#nanoTime() ticks}
>      * thereafter. This ensures there's no clock skew problems inside a single trace.
>      *
>      * See {@link Tracing#clock(TraceContext)}
>      */
>     public Builder clock(Clock clock) {
>       if (clock == null) throw new NullPointerException("clock == null");
>       this.clock = clock;
>       return this;
>     }
> ```

Oh, I don't know it exists. How do I use it?

**Comment by adriancole** [comment]
If you have a different clock you can specify it. to change timestamps externally is also possible (Span.start(long)) just, this can create skew in a trace. Mostly you don't need to change this unless your operating system has a better clock than java can provide.

(this is implemented in brave.internal.Platform)

hope these notes help. if you have more questions, try gitter https://gitter.im/openzipkin/zipkin

**Comment by wangliang1986** [comment]
> 
> 
> If you have a different clock you can specify it. to change timestamps externally is also possible (Span.start(long)) just, this can create skew in a trace. Mostly you don't need to change this unless your operating system has a better clock than java can provide.
> 
> (this is implemented in brave.internal.Platform)
> 
> hope these notes help. if you have more questions, try gitter https://gitter.im/openzipkin/zipkin

In spring cloud, different hosts will have different times, and I am lazy to do synchronization, so I hope to achieve the same time standard through the same time source.

**Comment by adriancole** [comment]
please use gitter to talk more. typically people use a service like NTP to change host clock instead of trying to change just the tracing clock (and not logs etc)

**Pull request closed without merging**
