### PR TITLE
Add http method to binary annotations

### PR DESCRIPTION
**Pull request by pavolloffay**
Hello, I would like to add HTTP method to the binary annotations.

@kristofa could you please review?

### CODE REVIEW

**Comment by adriancole** [comment]
Iirc HTTP method is also the default span name. If we do this, we add 15
bytes to the most popular spans. I'd like another plus one from a higher
scale user before merging.

**Comment by pavolloffay** [comment]
I think it is better to have it explicitly recorded as an HTTP method in binary annotations. What if someone is tracing JMS or even other technologies?

**Comment by kristofa** [comment]
I agree with Adrian. 
If we would trace JMS or other protocols we can add custom annotations like we already do for grpc, mysql.

**Comment by pavolloffay** [comment]
@kristofa @adriancole thanks for a feedback, I'm closing it.

**Pull request closed without merging**
