### PR TITLE
add alibaba druid support more database tracing sql query

### PR DESCRIPTION
**Pull request by IAMTJW**
This is a tracing filter for Alibaba Druid 1.1.14 (https://github.com/alibaba/druid), support more databases。

### CODE REVIEW

**Comment by devinsba** [comment]
To remove ambiguity with Apache Druid (incubating) it would be good to change the name of this slightly, perhaps: `brave-instrumentation-druidcp`

**Comment by adriancole** [comment]
tough call as I also thought about Apache druid. most of our libs associate
with the jar name and the only problem (bikeshed as it may be) besides that
is I dont see druid being named druidcp anywhere.. another option would be
to include Alibaba but if this goes to Apache then that would drift.
however.. heh it would have to as druid is already in Apache as you mention
;)

so I guess I would suggest adding alibaba into the name unless druid is
called druidcp but I just missed noticing that.

**Comment by adriancole** [comment]
Hi, @IAMTJW I do believe that this feature will be diversely used, but we do have a policy of establishing that before we merge. Otherwise known as rule of three https://github.com/openzipkin/brave/blob/master/HACKING.md#forks-are-welcome

Please find 3 people who will use this feature to 👍 or otherwise comment on this change so we know that people besides you will help support this long term. Often a mix of interest from maintainers and end users are helpful.

**Comment by IAMTJW** [comment]
> Hi, @IAMTJW I do believe that this feature will be diversely used, but we do have a policy of establishing that before we merge. Otherwise known as rule of three https://github.com/openzipkin/brave/blob/master/HACKING.md#forks-are-welcome
> 
> Please find 3 people who will use this feature to  or otherwise comment on this change so we know that people besides you will help support this long term. Often a mix of interest from maintainers and end users are helpful.

It will be useful and Now we use postgresql as database service and we need it to tracing pg sql query.

**Comment by adriancole** [comment]
hi @IAMTJW I understand you are interested in this. I meant to say can you help find others who are also interested?

**Pull request closed without merging**
