### PR TITLE
issue-1340: finish grpc span in TracingServerCallListener#onCancel

### PR DESCRIPTION
**Pull request by osadchuk-roman**

### CODE REVIEW

**Comment by osadchuk-roman** [comment]
related to https://github.com/openzipkin/brave/issues/1340

**Comment by jcchavezs** [comment]
Could you add a failing test?

**Comment by osadchuk-roman** [comment]
> Could you add a failing test?

done

**Comment by osadchuk-roman** [comment]
@jcchavezs could you please start pr workflow again?

**Comment by ajax-osadchuk-r** [comment]
@jcchavezs Is this PR good for merging? If yes - please merge it

**Comment by jcchavezs** [comment]
I still don't see the failing test case :(.

**Comment by codefromthecrypt** [comment]
closing as without a test this isn't something to merge. we need to know the lifecycle relationship between onCancel and onHalfClose, specifically this assumes the latter isn't called.

**Pull request closed without merging**
