### PR TITLE
Fixes places where we didn't use provided scope

### PR DESCRIPTION
**Pull request by adriancole**
Provided helps us not interfere with user-defined versions

### CODE REVIEW

**Comment by adriancole** [comment]
cc @jorgheymans

**Comment by jorgheymans** [comment]
:+1:

**Comment by adriancole** [comment]
about your comment on p6spy.. 
> tend to agree for very common libs like guava / commons-* / jackson etc .. but very likely p6spy is not present in a project that was not already tracing so in this case it's probably ok to more lean towards convenience.

it actually makes sense. I can take out provided and put rationale instead (ex unlikeliness that users are already using it w/o tracing, so leave as compile scope) cc @felixbarny

**Comment by felixbarny** [comment]
I also chose to use compile scope for p6spy in stagemonitor.

**Comment by adriancole** [comment]
Cool will note and continue. Thx for the feedback!

**Pull request merged**
