### PR TITLE
WIP: adds MutableTraceContext

### PR DESCRIPTION
**Pull request by adriancole**
This is a work in progress to allow multiple trace context plugins to participate without thrashing. For example, you can look to see if a trace has been extracted yet or not, or add your "extra" stuff without making a new copy.

### CODE REVIEW

**Comment by yurishkuro** [comment]
> make 100% sampling something practical

neat. What's the primary bottleneck? Memory allocations?

**Comment by adriancole** [comment]
memory allocation is the primary thing for this. even though we are
careful, due to composition of propagation decorators.. when each copies
eachother.. there can be lots of memory allocated per request, like KiB per
request. other work on MutableSpan is similar except for the reporting
side. ex if no zipkin is used we can allocate less (for example metrics or
a different export entirely)

We want to support 100% collection and also help with downside
(allocation).. here it is firstly by not recreating data for collaborative
extraction, and later by reusing objects like @felixbarny does in the
elastic amp agent.

If we encourage 100% without this sort of work, we have a problem where gc
pressure load could affect apps and ironically timing ;)

this needs banging around because the api still needs to be clear.. I am
not confident on it yet... worst case we temporarily move this stuff
internal for a while.

**Comment by adriancole** [comment]
OK even with no object recycling, the results are quite good for composite extraction (ex b3 + extra fields) which is relatively common. 3x performance and an order of magnitude when extracting nothing.

```
Benchmark                                                  Mode  Cnt    Score   Error   Units
ExtraFieldPropagationBenchmarks.extract                   thrpt   15    3.386 ± 0.036  ops/us
ExtraFieldPropagationBenchmarks.extract_no_extra          thrpt   15    3.597 ± 0.077  ops/us
ExtraFieldPropagationBenchmarks.extract_nothing           thrpt   15    6.735 ± 0.219  ops/us
ExtraFieldPropagationBenchmarks.inject                    thrpt   15   12.885 ± 0.176  ops/us
ExtraFieldPropagationBenchmarks.mutable_extract           thrpt   15    9.779 ± 0.441  ops/us
ExtraFieldPropagationBenchmarks.mutable_extract_no_extra  thrpt   15   12.214 ± 0.462  ops/us
ExtraFieldPropagationBenchmarks.mutable_extract_nothing   thrpt   15  119.384 ± 2.792  ops/us
```

**Comment by adriancole** [comment]
backfilled https://github.com/openzipkin/brave/pull/758 to capture prior state as internals changed even on the base case

**Comment by adriancole** [comment]
I ran the benchmarks again after normalizing things.. I'm at the moment not confident the reduced overhead is worth it alone to justify introducing a couple apis in the middle of a version. It might be a brave v6 type of deal, where we can break api.

That said, I do think internal refactoring here is worthwhile extracting as it reduces allocation anyway. 

Next step: extract the good things from here, but without any of the public api changes.

```
Benchmark                                                                                      Mode     Cnt     Score    Error   Units
GrpcPropagationBenchmarks.extract_b3                                                         sample  475065     0.326 ±  0.023   us/op
GrpcPropagationBenchmarks.extract_b3:extract_b3·p0.00                                        sample             0.245            us/op
GrpcPropagationBenchmarks.extract_b3:extract_b3·p0.50                                        sample             0.270            us/op
GrpcPropagationBenchmarks.extract_b3:extract_b3·p0.90                                        sample             0.282            us/op
GrpcPropagationBenchmarks.extract_b3:extract_b3·p0.95                                        sample             0.302            us/op
GrpcPropagationBenchmarks.extract_b3:extract_b3·p0.99                                        sample             0.572            us/op
GrpcPropagationBenchmarks.extract_b3:extract_b3·p0.999                                       sample            10.288            us/op
GrpcPropagationBenchmarks.extract_b3:extract_b3·p0.9999                                      sample            20.767            us/op
GrpcPropagationBenchmarks.extract_b3:extract_b3·p1.00                                        sample          2248.704            us/op
GrpcPropagationBenchmarks.extract_b3:·gc.alloc.rate                                          sample      15  1285.263 ± 76.913  MB/sec
GrpcPropagationBenchmarks.extract_b3:·gc.alloc.rate.norm                                     sample      15   504.056 ±  0.014    B/op
GrpcPropagationBenchmarks.extract_b3:·gc.churn.PS_Eden_Space                                 sample      15  1285.238 ± 88.909  MB/sec
GrpcPropagationBenchmarks.extract_b3:·gc.churn.PS_Eden_Space.norm                            sample      15   503.876 ± 12.003    B/op
GrpcPropagationBenchmarks.extract_b3:·gc.churn.PS_Survivor_Space                             sample      15     0.252 ±  0.048  MB/sec
GrpcPropagationBenchmarks.extract_b3:·gc.churn.PS_Survivor_Space.norm                        sample      15     0.099 ±  0.022    B/op
GrpcPropagationBenchmarks.extract_b3:·gc.count                                               sample      15   281.000           counts
GrpcPropagationBenchmarks.extract_b3:·gc.time                                                sample      15   143.000               ms
GrpcPropagationBenchmarks.extract_b3_nothing                                                 sample  500407     0.050 ±  0.001   us/op
GrpcPropagationBenchmarks.extract_b3_nothing:extract_b3_nothing·p0.00                        sample             0.003            us/op
GrpcPropagationBenchmarks.extract_b3_nothing:extract_b3_nothing·p0.50                        sample             0.046            us/op
GrpcPropagationBenchmarks.extract_b3_nothing:extract_b3_nothing·p0.90                        sample             0.050            us/op
GrpcPropagationBenchmarks.extract_b3_nothing:extract_b3_nothing·p0.95                        sample             0.055            us/op
GrpcPropagationBenchmarks.extract_b3_nothing:extract_b3_nothing·p0.99                        sample             0.061            us/op
GrpcPropagationBenchmarks.extract_b3_nothing:extract_b3_nothing·p0.999                       sample             0.186            us/op
GrpcPropagationBenchmarks.extract_b3_nothing:extract_b3_nothing·p0.9999                      sample            10.479            us/op
GrpcPropagationBenchmarks.extract_b3_nothing:extract_b3_nothing·p1.00                        sample            36.608            us/op
GrpcPropagationBenchmarks.extract_b3_nothing:·gc.alloc.rate                                  sample      15     0.093 ±  0.022  MB/sec
GrpcPropagationBenchmarks.extract_b3_nothing:·gc.alloc.rate.norm                             sample      15     0.001 ±  0.001    B/op
GrpcPropagationBenchmarks.extract_b3_nothing:·gc.count                                       sample      15       ≈ 0           counts
GrpcPropagationBenchmarks.extract_both                                                       sample  321576     0.255 ±  0.018   us/op
GrpcPropagationBenchmarks.extract_both:extract_both·p0.00                                    sample             0.176            us/op
GrpcPropagationBenchmarks.extract_both:extract_both·p0.50                                    sample             0.206            us/op
GrpcPropagationBenchmarks.extract_both:extract_both·p0.90                                    sample             0.220            us/op
GrpcPropagationBenchmarks.extract_both:extract_both·p0.95                                    sample             0.228            us/op
GrpcPropagationBenchmarks.extract_both:extract_both·p0.99                                    sample             0.405            us/op
GrpcPropagationBenchmarks.extract_both:extract_both·p0.999                                   sample            10.528            us/op
GrpcPropagationBenchmarks.extract_both:extract_both·p0.9999                                  sample            20.416            us/op
GrpcPropagationBenchmarks.extract_both:extract_both·p1.00                                    sample           736.256            us/op
GrpcPropagationBenchmarks.extract_both:·gc.alloc.rate                                        sample      15   992.233 ±  7.932  MB/sec
GrpcPropagationBenchmarks.extract_both:·gc.alloc.rate.norm                                   sample      15   288.037 ±  0.005    B/op
GrpcPropagationBenchmarks.extract_both:·gc.churn.PS_Eden_Space                               sample      15   990.133 ± 27.711  MB/sec
GrpcPropagationBenchmarks.extract_both:·gc.churn.PS_Eden_Space.norm                          sample      15   287.411 ±  7.002    B/op
GrpcPropagationBenchmarks.extract_both:·gc.churn.PS_Survivor_Space                           sample      15     0.229 ±  0.055  MB/sec
GrpcPropagationBenchmarks.extract_both:·gc.churn.PS_Survivor_Space.norm                      sample      15     0.067 ±  0.016    B/op
GrpcPropagationBenchmarks.extract_both:·gc.count                                             sample      15   296.000           counts
GrpcPropagationBenchmarks.extract_both:·gc.time                                              sample      15   146.000               ms
GrpcPropagationBenchmarks.extract_both_no_tags                                               sample  520056     0.072 ±  0.007   us/op
GrpcPropagationBenchmarks.extract_both_no_tags:extract_both_no_tags·p0.00                    sample             0.011            us/op
GrpcPropagationBenchmarks.extract_both_no_tags:extract_both_no_tags·p0.50                    sample             0.059            us/op
GrpcPropagationBenchmarks.extract_both_no_tags:extract_both_no_tags·p0.90                    sample             0.068            us/op
GrpcPropagationBenchmarks.extract_both_no_tags:extract_both_no_tags·p0.95                    sample             0.071            us/op
GrpcPropagationBenchmarks.extract_both_no_tags:extract_both_no_tags·p0.99                    sample             0.121            us/op
GrpcPropagationBenchmarks.extract_both_no_tags:extract_both_no_tags·p0.999                   sample             0.759            us/op
GrpcPropagationBenchmarks.extract_both_no_tags:extract_both_no_tags·p0.9999                  sample            10.704            us/op
GrpcPropagationBenchmarks.extract_both_no_tags:extract_both_no_tags·p1.00                    sample           704.512            us/op
GrpcPropagationBenchmarks.extract_both_no_tags:·gc.alloc.rate                                sample      15  1792.781 ± 10.719  MB/sec
GrpcPropagationBenchmarks.extract_both_no_tags:·gc.alloc.rate.norm                           sample      15    80.005 ±  0.001    B/op
GrpcPropagationBenchmarks.extract_both_no_tags:·gc.churn.PS_Eden_Space                       sample      15  1791.586 ± 31.044  MB/sec
GrpcPropagationBenchmarks.extract_both_no_tags:·gc.churn.PS_Eden_Space.norm                  sample      15    79.952 ±  1.297    B/op
GrpcPropagationBenchmarks.extract_both_no_tags:·gc.churn.PS_Survivor_Space                   sample      15     0.210 ±  0.055  MB/sec
GrpcPropagationBenchmarks.extract_both_no_tags:·gc.churn.PS_Survivor_Space.norm              sample      15     0.009 ±  0.002    B/op
GrpcPropagationBenchmarks.extract_both_no_tags:·gc.count                                     sample      15   286.000           counts
GrpcPropagationBenchmarks.extract_both_no_tags:·gc.time                                      sample      15   144.000               ms
GrpcPropagationBenchmarks.extract_both_nothing                                               sample  502826     0.048 ±  0.001   us/op
GrpcPropagationBenchmarks.extract_both_nothing:extract_both_nothing·p0.00                    sample             0.007            us/op
GrpcPropagationBenchmarks.extract_both_nothing:extract_both_nothing·p0.50                    sample             0.043            us/op
GrpcPropagationBenchmarks.extract_both_nothing:extract_both_nothing·p0.90                    sample             0.050            us/op
GrpcPropagationBenchmarks.extract_both_nothing:extract_both_nothing·p0.95                    sample             0.050            us/op
GrpcPropagationBenchmarks.extract_both_nothing:extract_both_nothing·p0.99                    sample             0.060            us/op
GrpcPropagationBenchmarks.extract_both_nothing:extract_both_nothing·p0.999                   sample             0.165            us/op
GrpcPropagationBenchmarks.extract_both_nothing:extract_both_nothing·p0.9999                  sample            10.512            us/op
GrpcPropagationBenchmarks.extract_both_nothing:extract_both_nothing·p1.00                    sample            46.720            us/op
GrpcPropagationBenchmarks.extract_both_nothing:·gc.alloc.rate                                sample      15     0.087 ±  0.021  MB/sec
GrpcPropagationBenchmarks.extract_both_nothing:·gc.alloc.rate.norm                           sample      15     0.001 ±  0.001    B/op
GrpcPropagationBenchmarks.extract_both_nothing:·gc.count                                     sample      15       ≈ 0           counts
GrpcPropagationBenchmarks.inject_b3                                                          sample  528404     0.275 ±  0.014   us/op
GrpcPropagationBenchmarks.inject_b3:inject_b3·p0.00                                          sample             0.202            us/op
GrpcPropagationBenchmarks.inject_b3:inject_b3·p0.50                                          sample             0.225            us/op
GrpcPropagationBenchmarks.inject_b3:inject_b3·p0.90                                          sample             0.277            us/op
GrpcPropagationBenchmarks.inject_b3:inject_b3·p0.95                                          sample             0.310            us/op
GrpcPropagationBenchmarks.inject_b3:inject_b3·p0.99                                          sample             0.592            us/op
GrpcPropagationBenchmarks.inject_b3:inject_b3·p0.999                                         sample             9.552            us/op
GrpcPropagationBenchmarks.inject_b3:inject_b3·p0.9999                                        sample            18.351            us/op
GrpcPropagationBenchmarks.inject_b3:inject_b3·p1.00                                          sample          1374.208            us/op
GrpcPropagationBenchmarks.inject_b3:·gc.alloc.rate                                           sample      15  2100.804 ± 27.658  MB/sec
GrpcPropagationBenchmarks.inject_b3:·gc.alloc.rate.norm                                      sample      15   752.052 ± 87.643    B/op
GrpcPropagationBenchmarks.inject_b3:·gc.churn.PS_Eden_Space                                  sample      15  2093.079 ± 40.125  MB/sec
GrpcPropagationBenchmarks.inject_b3:·gc.churn.PS_Eden_Space.norm                             sample      15   749.037 ± 85.144    B/op
GrpcPropagationBenchmarks.inject_b3:·gc.churn.PS_Survivor_Space                              sample      15     0.244 ±  0.072  MB/sec
GrpcPropagationBenchmarks.inject_b3:·gc.churn.PS_Survivor_Space.norm                         sample      15     0.087 ±  0.028    B/op
GrpcPropagationBenchmarks.inject_b3:·gc.count                                                sample      15   286.000           counts
GrpcPropagationBenchmarks.inject_b3:·gc.time                                                 sample      15   147.000               ms
GrpcPropagationBenchmarks.inject_both                                                        sample  312695     0.479 ±  0.025   us/op
GrpcPropagationBenchmarks.inject_both:inject_both·p0.00                                      sample             0.351            us/op
GrpcPropagationBenchmarks.inject_both:inject_both·p0.50                                      sample             0.383            us/op
GrpcPropagationBenchmarks.inject_both:inject_both·p0.90                                      sample             0.427            us/op
GrpcPropagationBenchmarks.inject_both:inject_both·p0.95                                      sample             0.504            us/op
GrpcPropagationBenchmarks.inject_both:inject_both·p0.99                                      sample             1.218            us/op
GrpcPropagationBenchmarks.inject_both:inject_both·p0.999                                     sample            11.189            us/op
GrpcPropagationBenchmarks.inject_both:inject_both·p0.9999                                    sample            32.613            us/op
GrpcPropagationBenchmarks.inject_both:inject_both·p1.00                                      sample           771.072            us/op
GrpcPropagationBenchmarks.inject_both:·gc.alloc.rate                                         sample      15  1843.494 ± 11.139  MB/sec
GrpcPropagationBenchmarks.inject_both:·gc.alloc.rate.norm                                    sample      15  1112.095 ±  0.010    B/op
GrpcPropagationBenchmarks.inject_both:·gc.churn.PS_Eden_Space                                sample      15  1837.559 ± 45.475  MB/sec
GrpcPropagationBenchmarks.inject_both:·gc.churn.PS_Eden_Space.norm                           sample      15  1108.445 ± 22.928    B/op
GrpcPropagationBenchmarks.inject_both:·gc.churn.PS_Survivor_Space                            sample      15     0.280 ±  0.090  MB/sec
GrpcPropagationBenchmarks.inject_both:·gc.churn.PS_Survivor_Space.norm                       sample      15     0.169 ±  0.055    B/op
GrpcPropagationBenchmarks.inject_both:·gc.count                                              sample      15   280.000           counts
GrpcPropagationBenchmarks.inject_both:·gc.time                                               sample      15   144.000               ms
GrpcPropagationBenchmarks.inject_both_no_tags                                                sample  405565     0.368 ±  0.019   us/op
GrpcPropagationBenchmarks.inject_both_no_tags:inject_both_no_tags·p0.00                      sample             0.237            us/op
GrpcPropagationBenchmarks.inject_both_no_tags:inject_both_no_tags·p0.50                      sample             0.296            us/op
GrpcPropagationBenchmarks.inject_both_no_tags:inject_both_no_tags·p0.90                      sample             0.333            us/op
GrpcPropagationBenchmarks.inject_both_no_tags:inject_both_no_tags·p0.95                      sample             0.402            us/op
GrpcPropagationBenchmarks.inject_both_no_tags:inject_both_no_tags·p0.99                      sample             0.995            us/op
GrpcPropagationBenchmarks.inject_both_no_tags:inject_both_no_tags·p0.999                     sample            10.768            us/op
GrpcPropagationBenchmarks.inject_both_no_tags:inject_both_no_tags·p0.9999                    sample            25.788            us/op
GrpcPropagationBenchmarks.inject_both_no_tags:inject_both_no_tags·p1.00                      sample           716.800            us/op
GrpcPropagationBenchmarks.inject_both_no_tags:·gc.alloc.rate                                 sample      15  1962.298 ± 32.058  MB/sec
GrpcPropagationBenchmarks.inject_both_no_tags:·gc.alloc.rate.norm                            sample      15   912.073 ±  0.008    B/op
GrpcPropagationBenchmarks.inject_both_no_tags:·gc.churn.PS_Eden_Space                        sample      15  1963.953 ± 56.500  MB/sec
GrpcPropagationBenchmarks.inject_both_no_tags:·gc.churn.PS_Eden_Space.norm                   sample      15   912.816 ± 20.399    B/op
GrpcPropagationBenchmarks.inject_both_no_tags:·gc.churn.PS_Survivor_Space                    sample      15     0.241 ±  0.083  MB/sec
GrpcPropagationBenchmarks.inject_both_no_tags:·gc.churn.PS_Survivor_Space.norm               sample      15     0.112 ±  0.039    B/op
GrpcPropagationBenchmarks.inject_both_no_tags:·gc.count                                      sample      15   288.000           counts
GrpcPropagationBenchmarks.inject_both_no_tags:·gc.time                                       sample      15   149.000               ms
GrpcPropagationBenchmarks.mutable_extract_b3                                                 sample  510225     0.286 ±  0.010   us/op
GrpcPropagationBenchmarks.mutable_extract_b3:mutable_extract_b3·p0.00                        sample             0.141            us/op
GrpcPropagationBenchmarks.mutable_extract_b3:mutable_extract_b3·p0.50                        sample             0.256            us/op
GrpcPropagationBenchmarks.mutable_extract_b3:mutable_extract_b3·p0.90                        sample             0.269            us/op
GrpcPropagationBenchmarks.mutable_extract_b3:mutable_extract_b3·p0.95                        sample             0.282            us/op
GrpcPropagationBenchmarks.mutable_extract_b3:mutable_extract_b3·p0.99                        sample             0.404            us/op
GrpcPropagationBenchmarks.mutable_extract_b3:mutable_extract_b3·p0.999                       sample             9.456            us/op
GrpcPropagationBenchmarks.mutable_extract_b3:mutable_extract_b3·p0.9999                      sample            17.205            us/op
GrpcPropagationBenchmarks.mutable_extract_b3:mutable_extract_b3·p1.00                        sample           753.664            us/op
GrpcPropagationBenchmarks.mutable_extract_b3:·gc.alloc.rate                                  sample      15  1156.820 ± 18.053  MB/sec
GrpcPropagationBenchmarks.mutable_extract_b3:·gc.alloc.rate.norm                             sample      15   424.049 ±  0.005    B/op
GrpcPropagationBenchmarks.mutable_extract_b3:·gc.churn.PS_Eden_Space                         sample      15  1155.091 ± 32.722  MB/sec
GrpcPropagationBenchmarks.mutable_extract_b3:·gc.churn.PS_Eden_Space.norm                    sample      15   423.422 ± 10.457    B/op
GrpcPropagationBenchmarks.mutable_extract_b3:·gc.churn.PS_Survivor_Space                     sample      15     0.212 ±  0.036  MB/sec
GrpcPropagationBenchmarks.mutable_extract_b3:·gc.churn.PS_Survivor_Space.norm                sample      15     0.078 ±  0.013    B/op
GrpcPropagationBenchmarks.mutable_extract_b3:·gc.count                                       sample      15   283.000           counts
GrpcPropagationBenchmarks.mutable_extract_b3:·gc.time                                        sample      15   141.000               ms
GrpcPropagationBenchmarks.mutable_extract_b3_nothing                                         sample  390840     0.043 ±  0.001   us/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:mutable_extract_b3_nothing·p0.00        sample             0.001            us/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:mutable_extract_b3_nothing·p0.50        sample             0.037            us/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:mutable_extract_b3_nothing·p0.90        sample             0.046            us/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:mutable_extract_b3_nothing·p0.95        sample             0.046            us/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:mutable_extract_b3_nothing·p0.99        sample             0.055            us/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:mutable_extract_b3_nothing·p0.999       sample             0.128            us/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:mutable_extract_b3_nothing·p0.9999      sample            10.448            us/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:mutable_extract_b3_nothing·p1.00        sample            22.912            us/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:·gc.alloc.rate                          sample      15     0.077 ±  0.017  MB/sec
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:·gc.alloc.rate.norm                     sample      15     0.001 ±  0.001    B/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:·gc.churn.PS_Eden_Space                 sample      15     2.811 ± 11.639  MB/sec
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:·gc.churn.PS_Eden_Space.norm            sample      15     0.021 ±  0.087    B/op
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:·gc.count                               sample      15     1.000           counts
GrpcPropagationBenchmarks.mutable_extract_b3_nothing:·gc.time                                sample      15     3.000               ms
GrpcPropagationBenchmarks.mutable_extract_both                                               sample  343575     0.082 ±  0.006   us/op
GrpcPropagationBenchmarks.mutable_extract_both:mutable_extract_both·p0.00                    sample             0.047            us/op
GrpcPropagationBenchmarks.mutable_extract_both:mutable_extract_both·p0.50                    sample             0.068            us/op
GrpcPropagationBenchmarks.mutable_extract_both:mutable_extract_both·p0.90                    sample             0.077            us/op
GrpcPropagationBenchmarks.mutable_extract_both:mutable_extract_both·p0.95                    sample             0.082            us/op
GrpcPropagationBenchmarks.mutable_extract_both:mutable_extract_both·p0.99                    sample             0.192            us/op
GrpcPropagationBenchmarks.mutable_extract_both:mutable_extract_both·p0.999                   sample             1.336            us/op
GrpcPropagationBenchmarks.mutable_extract_both:mutable_extract_both·p0.9999                  sample            10.602            us/op
GrpcPropagationBenchmarks.mutable_extract_both:mutable_extract_both·p1.00                    sample           598.016            us/op
GrpcPropagationBenchmarks.mutable_extract_both:·gc.alloc.rate                                sample      15  2588.453 ± 23.942  MB/sec
GrpcPropagationBenchmarks.mutable_extract_both:·gc.alloc.rate.norm                           sample      15   176.007 ±  0.001    B/op
GrpcPropagationBenchmarks.mutable_extract_both:·gc.churn.PS_Eden_Space                       sample      15  2572.478 ± 71.182  MB/sec
GrpcPropagationBenchmarks.mutable_extract_both:·gc.churn.PS_Eden_Space.norm                  sample      15   174.915 ±  4.264    B/op
GrpcPropagationBenchmarks.mutable_extract_both:·gc.churn.PS_Survivor_Space                   sample      15     0.245 ±  0.058  MB/sec
GrpcPropagationBenchmarks.mutable_extract_both:·gc.churn.PS_Survivor_Space.norm              sample      15     0.017 ±  0.004    B/op
GrpcPropagationBenchmarks.mutable_extract_both:·gc.count                                     sample      15   290.000           counts
GrpcPropagationBenchmarks.mutable_extract_both:·gc.time                                      sample      15   141.000               ms
GrpcPropagationBenchmarks.mutable_extract_both_no_tags                                       sample  333371     0.062 ±  0.002   us/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:mutable_extract_both_no_tags·p0.00    sample             0.003            us/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:mutable_extract_both_no_tags·p0.50    sample             0.050            us/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:mutable_extract_both_no_tags·p0.90    sample             0.062            us/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:mutable_extract_both_no_tags·p0.95    sample             0.065            us/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:mutable_extract_both_no_tags·p0.99    sample             0.099            us/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:mutable_extract_both_no_tags·p0.999   sample             1.062            us/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:mutable_extract_both_no_tags·p0.9999  sample            10.656            us/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:mutable_extract_both_no_tags·p1.00    sample            48.896            us/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:·gc.alloc.rate                        sample      15  1598.306 ± 31.844  MB/sec
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:·gc.alloc.rate.norm                   sample      15    56.003 ±  0.001    B/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:·gc.churn.PS_Eden_Space               sample      15  1600.571 ± 42.009  MB/sec
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:·gc.churn.PS_Eden_Space.norm          sample      15    56.083 ±  0.998    B/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:·gc.churn.PS_Survivor_Space           sample      15     0.162 ±  0.054  MB/sec
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:·gc.churn.PS_Survivor_Space.norm      sample      15     0.006 ±  0.002    B/op
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:·gc.count                             sample      15   296.000           counts
GrpcPropagationBenchmarks.mutable_extract_both_no_tags:·gc.time                              sample      15   143.000               ms
GrpcPropagationBenchmarks.mutable_extract_both_nothing                                       sample  377131     0.045 ±  0.001   us/op
GrpcPropagationBenchmarks.mutable_extract_both_nothing:mutable_extract_both_nothing·p0.00    sample             0.010            us/op
GrpcPropagationBenchmarks.mutable_extract_both_nothing:mutable_extract_both_nothing·p0.50    sample             0.040            us/op
GrpcPropagationBenchmarks.mutable_extract_both_nothing:mutable_extract_both_nothing·p0.90    sample             0.046            us/op
GrpcPropagationBenchmarks.mutable_extract_both_nothing:mutable_extract_both_nothing·p0.95    sample             0.047            us/op
GrpcPropagationBenchmarks.mutable_extract_both_nothing:mutable_extract_both_nothing·p0.99    sample             0.055            us/op
GrpcPropagationBenchmarks.mutable_extract_both_nothing:mutable_extract_both_nothing·p0.999   sample             0.133            us/op
GrpcPropagationBenchmarks.mutable_extract_both_nothing:mutable_extract_both_nothing·p0.9999  sample            10.485            us/op
GrpcPropagationBenchmarks.mutable_extract_both_nothing:mutable_extract_both_nothing·p1.00    sample            32.192            us/op
GrpcPropagationBenchmarks.mutable_extract_both_nothing:·gc.alloc.rate                        sample      15     0.079 ±  0.015  MB/sec
GrpcPropagationBenchmarks.mutable_extract_both_nothing:·gc.alloc.rate.norm                   sample      15     0.001 ±  0.001    B/op
GrpcPropagationBenchmarks.mutable_extract_both_nothing:·gc.count                             sample      15       ≈ 0           counts

Process finished with exit code 0
```

**Comment by adriancole** [comment]
going to close this after https://github.com/openzipkin/brave/pull/759

**Comment by adriancole** [comment]
closing this as it isn't feasible until we can break api

**Pull request closed without merging**
