### PR TITLE
Deprecates the brave-cxf3 extension in favor of Apache CXF one

### LINKED ISSUE #294: Report of trace not continuing between CXF Web Services
If someone can validate this, it would be most appreciated. Basically to know if this is a code concern (bug or usage bug), configuration one (propagation state disconnect due to something not being wrapped), or a misunderstood normal behavior (like the trace ids being different is normal)

cc @cschneider @reta @podsiedzik

Copying this from a gitter post from @auntscrewy 
> Here is my junit test. I want to call a service that calls a service. I believe I would want the traceId to be the same. Right?
```java
package com.github.kristofa.brave.cxf3.integration;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.Assert.assertEquals;
import javax.jws.WebMethod;
import org.apache.cxf.endpoint.Server;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.apache.cxf.jaxws.JaxWsServerFactoryBean;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import com.github.kristofa.brave.Brave;
import com.github.kristofa.brave.cxf3.BraveClientInInterceptor;
import com.github.kristofa.brave.cxf3.BraveClientOutInterceptor;
import com.github.kristofa.brave.cxf3.BraveServerInInterceptor;
import com.github.kristofa.brave.cxf3.BraveServerOutInterceptor;
import com.github.kristofa.brave.cxf3.ReporterForTesting;
public class ITBraveCxfInterceptorsJws
{
Server server;
FooService client;
static ReporterForTesting reporter = new ReporterForTesting();
Brave brave = new Brave.Builder().reporter(reporter).build();
BraveServerInInterceptor serverInInterceptor = BraveServerInInterceptor.create(brave);
BraveServerOutInterceptor serverOutInterceptor = BraveServerOutInterceptor.create(brave);
BraveClientInInterceptor clientInInterceptor = BraveClientInInterceptor.create(brave);
BraveClientOutInterceptor clientOutInterceptor = BraveClientOutInterceptor.create(brave);
public interface FooService
{
    @WebMethod
    String foo();
}

public static class DefaultFooService implements FooService
{
    private static int cnt = 0;
    // ReporterForTesting reporter = new ReporterForTesting();
    Brave brave = new Brave.Builder().reporter(reporter).build();
    BraveClientInInterceptor clientInInterceptor = BraveClientInInterceptor.create(brave);
    BraveClientOutInterceptor clientOutInterceptor = BraveClientOutInterceptor.create(brave);

    @Override
    public String foo()
    {

        if (cnt++ == 0)
        {
            String url = "http://localhost:9000/test";


            JaxWsProxyFactoryBean clientFactory = new JaxWsProxyFactoryBean();
            clientFactory.setAddress(url);
            clientFactory.setServiceClass(FooService.class);
            clientFactory.getInInterceptors().add(clientInInterceptor);
            clientFactory.getOutInterceptors().add(clientOutInterceptor);
            FooService client = (FooService) clientFactory.create();
            return client.foo();
        }

        return "foo";
    }
}

@Before
public void setUp() throws Exception
{
    // setup server
    String url = "http://localhost:9000/test";

    JaxWsServerFactoryBean serverFactory = new JaxWsServerFactoryBean();
    serverFactory.setAddress(url);
    serverFactory.setServiceClass(FooService.class);
    serverFactory.setServiceBean(new DefaultFooService());
    serverFactory.getInInterceptors().add(serverInInterceptor);
    serverFactory.getOutInterceptors().add(serverOutInterceptor);
    this.server = serverFactory.create();

    // setup client
    JaxWsProxyFactoryBean clientFactory = new JaxWsProxyFactoryBean();
    clientFactory.setAddress(url);
    clientFactory.setServiceClass(FooService.class);
    clientFactory.getInInterceptors().add(clientInInterceptor);
    clientFactory.getOutInterceptors().add(clientOutInterceptor);
    this.client = (FooService) clientFactory.create();
}

@After
public void tearDown() throws Exception
{
    if (server != null)
    {
        server.stop();
    }
}

@Test
public void testInterceptors() throws Exception
{
    client.foo();
    for (zipkin.Span span : reporter.getCollectedSpans())
    {
        System.out.println(span.toString());
    }
    assertThat(reporter.getCollectedSpans()).hasSize(4);
    assertEquals(reporter.getCollectedSpans().get(0).traceId,
            reporter.getCollectedSpans().get(2).traceId);
}
}
```

### LINKED ISSUE #354: Initiate deprecation of the brave-cxf3 extension in favor of Apache CXF one
Hey guys!

Following the proposal (https://github.com/openzipkin/brave/issues/313), Apache CXF now has a dedicated support of `Brave` as a distributed tracing provider. The next steps would be to communicate the change to community, deprecate `brave-cxf3` extension and eventually remove it from `Brave` distribution.

As the first steps to start with:
 - update `brave-cxf3` README file to raise the awareness about upcoming deprecations, outline the migration path
 - annotate relevant public `brave-cxf3` API as `@Deprecated`, document the replacement 

Thanks!

Best Regards,
    Andriy Redko

### PR DESCRIPTION
**Pull request by adriancole**
The last release to publish this is 4.1

Fixes #354
Closes #294
Closes #304

### CODE REVIEW

**Comment by adriancole** [comment]
cc @reta

**Comment by adriancole** [comment]
merging for release as the plan was agreed upon a while back. happy for any rewording comments after the fact as needed.

**Comment by reta** [comment]
Thanks a lot @adriancole, I will start working on documentation & migration guides shortly, sorry for delay ...

**Comment by adriancole** [comment]
cool. just PR the brave-cxf3 readme when you have it. thanks!

**Comment by reta** [comment]
@adriancole will do, thanks!

**Pull request merged**
