### PR TITLE
Export package com.github.kristofa.brave.internal

### PR DESCRIPTION
**Pull request by cschneider**
See issue #268

### CODE REVIEW

**Comment by adriancole** [comment]
looking at #275 there's only a Util class left. I really wish OSGi could be reasonable.

**Comment by adriancole** [comment]
So Util has only checkNotX methods, and it would be nice to not have to export the internal package, and also nice to not have to copy or move the Util class as they are effectively internal to brave's group.

Essentially, it would be nice for us to be able to support external users of brave's "real" public types (i.e. non-internal ones) without eliminating or complicating the checkNotNull story (internal types), which have not been a problem so far.

I'd like to avoid blanket exporting internal as that feels wrong, as the only code that should use this would be code under our control. In other words, I'd like to not make our tacit internal package explicitly scoped for others (and then later have questions if we remove those types or add more into the internal subpackages).

@njbartlett suggested mandatory export attributes is a way out of this

**Comment by adriancole** [comment]
next step: look at impact of the related mail thread and adjust https://mail.osgi.org/pipermail/osgi-dev/2016-November/005880.html

**Comment by cschneider** [comment]
I applied the mandatory attribute like recommended by Tim and it works fine. We do not need special setup on the bundles using this. So looks good to me.

**Comment by adriancole** [comment]
fantastico!

**Pull request merged**
