### PR TITLE
Increase timeout to 10 seconds for tests

### PR DESCRIPTION
**Pull request by minwoox**
Related: https://github.com/line/armeria/pull/2559
The tests could take longer because of instrumenting test coverage.
So I think it's better to increase it upto 10 seconds.

### CODE REVIEW

**Comment by adriancole** [comment]
maybe just for consistency, hit the others?

```bash
$ ag 'Timeout.seconds'
instrumentation/dubbo-rpc/src/test/java/brave/dubbo/rpc/ITTracingFilter.java
39:  @Rule public TestRule globalTimeout = new DisableOnDebug(Timeout.seconds(5)); // max per method

instrumentation/http-tests/src/main/java/brave/test/http/ITHttp.java
102:  @Rule public TestRule globalTimeout = new DisableOnDebug(Timeout.seconds(5)); // max per method

instrumentation/dubbo/src/test/java/brave/dubbo/ITTracingFilter.java
40:  @Rule public TestRule globalTimeout = new DisableOnDebug(Timeout.seconds(5)); // max per method
```

**Comment by minwoox** [comment]
Ah yes. Fixed. Thanks. 😉

**Comment by adriancole** [comment]
thanks for pushing this upstream!

**Comment by minwoox** [comment]
Hope to do it more. 😆

**Pull request merged**
