### PR TITLE
Dubbo3 support

### PR DESCRIPTION
**Pull request by ShenFeng312**
Hello! Due to Dubbo 2.7 no longer being maintained and an increasing number of users reporting that Brave cannot run on Dubbo 3, we have decided to upgrade the version of Dubbo. This version has smaller changes compared to the previous PR and is compatible with the features of Dubbo 2.7.

### CODE REVIEW

**Comment by ShenFeng312** [comment]
@jcchavezs

**Comment by jcchavezs** [comment]
I am sorry for the delay. Running it.

**Comment by ShenFeng312** [comment]
@jcchavezs  Hi, could you please help me rerun the unit tests?

**Comment by jcchavezs** [comment]
This is a breaking change isn't? Will users in Dubbo 2.x able to consume this library? If not maybe we want to do a whole new package.

**Comment by ShenFeng312** [comment]
> This is a breaking change isn't? Will users in Dubbo 2.x able to consume this library? If not maybe we want to do a whole new package.

 users in Dubbo 2.x able to consume this library

**Review by codefromthecrypt — APPROVED** [review]
I'm approving this, but we should add an invoker test to verify 2.7 still works. I hope you can raise a PR to do that. You can see examples of this in other projects which have a src/it directory. Thanks a lot!

**Pull request merged**
